baseurl = "https://m-mirz.github.io"
languageCode = "en-us"
paginate = 5
title = "Markus' blog"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "en"
